### ISSUE TITLE
是不是机场普遍不做保护用户隐私的事，还是说个别的有

### ISSUE THREAD

**Issue by sjush** [cadencando/SSSSRV2RayTrojanClash#3]
我选了很久，选了ytoo。
1. 节点区域很多，应该算是大机场了，可我看服务条款似乎没有任何保护用户隐私的相关内容，全部是免责条款。
是否意味着他从一开始就没打算对用户负责，还是说这是机场的普遍规则。
2. windows端仅支持停止维护的ss、ssr和闭源的cfw。不支持开源的v2rayN。像这么关键且重要的软件，不更应该开源吗？否则在这种黑暗地带岂不是引颈待戮？
希望得到回复，感谢！

**Comment by sjush** [comment]
首先感谢分享
因为一些原因，我需要一些冷门国家的ip。tagInternet 和 ytoo是最好的选择。但是在注册tag的时候发现只能用指定的几个邮箱注册，而且都是可以关联个人信息的。隐私无关的邮箱都无法使用，这不只是个验证么。
真不能怪我疑神疑鬼，实在是他们的操作全都是目的不单纯的。敏感地带不避嫌，似乎跟承认也没什么区别

**Comment by cadencando** [comment]
机场本来就是灰色地带，你翻出去做了什么，想知道的人都能知道，至于你说的网站上的条款看看就好，你信你就输了，真出了问题，难道还能到法院调解吗？？？
windows端的v2rayN是支持的，可以导入trojan格式的订阅使用，ss是因为v2rayN 不支持 obfs插件所以导入不了。开不开源不是以你的意志为转移的，东西发布出来也没有人强迫你用，选择权在于你自己。

总的来说：作为成年人，要自己对自己负责。如果你接受不了，可以拒绝使用。没有人会强迫你必须要用。

**Comment by cadencando** [comment]
> 我选了很久，选了ytoo。
> 
> 1. 节点区域很多，应该算是大机场了，可我看服务条款似乎没有任何保护用户隐私的相关内容，全部是免责条款。
>    是否意味着他从一开始就没打算对用户负责，还是说这是机场的普遍规则。
> 2. windows端仅支持停止维护的ss、ssr和闭源的cfw。不支持开源的v2rayN。像这么关键且重要的软件，不更应该开源吗？否则在这种黑暗地带岂不是引颈待戮？
>    希望得到回复，感谢！

机场本来就是灰色地带，你翻出去做了什么，想知道的人都能知道，至于你说的网站上的条款看看就好，你信你就输了，真出了问题，难道还能到法院调解吗？？？
windows端的v2rayN是支持的，可以导入trojan格式的订阅使用，ss是因为v2rayN 不支持 obfs插件所以导入不了。开不开源不是以你的意志为转移的，东西发布出来也没有人强迫你用，选择权在于你自己。

**Comment by vtroisWhite** [comment]
首先，cfw只是个客户端工具，其内核clash是开源的，其次，clash只是支持各种协议的内核，支持ss、ssr、vmess、trojan什么的，所以本质上讲，clash和使用v2rayN没什么区别，现在都用clash的原因是因为其订阅功能很强大，可以配置各种路由分流规则与DNS解析规则，并不是因为闭源会留有什么后门，只要你不用对方的提供下载的工具就理论上不会有问题。
最后，如果你很在乎数据安全，那么还是建议你学习下如何自建一套。

**Comment by vtroisWhite** [comment]
> 我选了很久，选了ytoo。
> 
> 1. 节点区域很多，应该算是大机场了，可我看服务条款似乎没有任何保护用户隐私的相关内容，全部是免责条款。
>    是否意味着他从一开始就没打算对用户负责，还是说这是机场的普遍规则。
> 2. windows端仅支持停止维护的ss、ssr和闭源的cfw。不支持开源的v2rayN。像这么关键且重要的软件，不更应该开源吗？否则在这种黑暗地带岂不是引颈待戮？
>    希望得到回复，感谢！

首先，cfw只是个客户端工具，其内核clash是开源的，其次，clash只是支持各种协议的内核，支持ss、ssr、vmess、trojan什么的，所以本质上讲，clash和使用v2rayN没什么区别，现在都用clash的原因是因为其订阅功能很强大，可以配置各种路由分流规则与DNS解析规则，并不是因为闭源会留有什么后门，只要你不用对方的提供下载的工具就理论上不会有问题。
最后，如果你很在乎数据安全，那么还是建议你学习下如何自建一套。
